# This file wont do us much good in this location, make sure you change the path as directed to continue!

name: Deploy to Github Packages

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-lastest]
                node-version: ['12']
        steps:
            - uses: actions/checkout@v1
            - name: npm install and build
              run: |
                  npm install
                  npm run build
            - uses: actions/upload-artifact@master
              with:
                  name: artifacts
                  path: public/

    publish-package:
        runs-on: ubuntu-latest
        needs: build
        name: publish to github packages
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Download built artifact
              uses: actions/download-artifact@master
              with:
                  name: artifacts
                  path: public
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
                  registry-url: "https://npm.pkg.github.com"
            - name: Publish package
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
